services:
  frontend:
    profiles: [ "prod" ]
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://app:8080}
    env_file:
      - path: ../.env
        required: false
    networks:
      - app-network

  frontend-dev:
    profiles: [ "dev" ]
    image: oven/bun:latest
    working_dir: /workspace
    command: >-
      sh -c "bun install && bun run dev"
    volumes:
      - ./:/workspace
      - bun-cache:/root/.bun
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL:-http://app-dev:8080}

      # OVO SE MENJA PO POTREBI.
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-http://10.237.43.148:3000}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://10.237.43.148:8080}

    env_file:
      - path: ../.env
        required: false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: shared-network
volumes:
  bun-cache: